name: dlfractals-env
channels:
  - conda-forge
dependencies:
  - python=2.7
  - numpy
  - scipy
  - pandas
  - matplotlib
  - jupyter
  - networkx
  - numpy
  - pyyaml
  - seaborn
  - pip:
    - tqdm
    - jupyterthemes
