# Global Arguments
globalParams:
#  createDataset: False
#  playDataset: 10
#  verbose: False
  train: local
  #modelTag: engg3130
  #rootDir: /plouffe/
  checkpointDir: /logs/lr05/
  checkpointName: lr05
# Dataset Arguments
datasetParams:
  syntheticDataset: plouffe
  datasetTag: plouffe-engg3130
  ratioDataset: 20
  datasetSize: 5000
# Neural Network Arguments
networkOptions:
  cellSize: 128
  hiddenSize: 256
# Hyperparameters
hyperparameters:
  numFrames: 200
  numNodes: 1600
  batchSize: 10
  maxEpoch: 40
  teacherForcingProb: 0.5
#  saveEvery: 10
#  validateEvery: 1
<<<<<<< HEAD
  learningRate: 0.001
=======
  learningRate: 0.5
>>>>>>> 533084e0e9339398ed62959f7a02ad249cd8f24f
#  learningRateDecay: 1
#  initMomentum: 0.5
#  finalMomentum: 0.9
