# Global Arguments
globalParams:
#  createDataset: False
#  playDataset: 10
#  verbose: False
  train: local
  #modelTag: engg3130
  #rootDir: /plouffe/
  checkpointDir: /logs/lr2000/
  checkpointName: lr2000
# Dataset Arguments
datasetParams:
  syntheticDataset: plouffe
  datasetTag: plouffe-engg3130
  ratioDataset: 20
  datasetSize: 2000
# Neural Network Arguments
networkOptions:
  cellSize: 128
  hiddenSize: 256
# Hyperparameters
hyperparameters:
  numFrames: 200
  numNodes: 100
  batchSize: 10
  maxEpoch: 40
  teacherForcingProb: 0.5
#  saveEvery: 10
#  validateEvery: 1
  learningRate: 0.005
#  learningRateDecay: 1
#  initMomentum: 0.5
#  finalMomentum: 0.9
